/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as platformRouteRouteImport } from './routes/(platform)/route'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AuthPathnameRouteImport } from './routes/auth/$pathname'
import { Route as platformDashboardRouteRouteImport } from './routes/(platform)/dashboard/route'
import { Route as platformAdminRouteRouteImport } from './routes/(platform)/admin/route'
import { Route as platformDashboardIndexRouteImport } from './routes/(platform)/dashboard/index'
import { Route as platformAdminIndexRouteImport } from './routes/(platform)/admin/index'
import { Route as platformOwnerDashboardRouteRouteImport } from './routes/(platform)/owner/dashboard/route'
import { Route as platformOwnerDashboardIndexRouteImport } from './routes/(platform)/owner/dashboard/index'
import { Route as platformAdminElectionsIndexRouteImport } from './routes/(platform)/admin/elections/index'
import { Route as platformAdminApprovalIndexRouteImport } from './routes/(platform)/admin/approval/index'
import { Route as platformAdminElectionsNewRouteImport } from './routes/(platform)/admin/elections/new'
import { Route as platformAdminElectionsElectionIdIndexRouteImport } from './routes/(platform)/admin/elections/$electionId/index'
import { Route as platformAdminElectionsElectionIdEditIndexRouteImport } from './routes/(platform)/admin/elections/$electionId/edit/index'
import { ServerRoute as ApiRpcSplatServerRouteImport } from './routes/api/rpc/$'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const platformRouteRoute = platformRouteRouteImport.update({
  id: '/(platform)',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/$pathname',
  path: '/$pathname',
  getParentRoute: () => AuthRouteRoute,
} as any)
const platformDashboardRouteRoute = platformDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => platformRouteRoute,
} as any)
const platformAdminRouteRoute = platformAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => platformRouteRoute,
} as any)
const platformDashboardIndexRoute = platformDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => platformDashboardRouteRoute,
} as any)
const platformAdminIndexRoute = platformAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const platformOwnerDashboardRouteRoute =
  platformOwnerDashboardRouteRouteImport.update({
    id: '/owner/dashboard',
    path: '/owner/dashboard',
    getParentRoute: () => platformRouteRoute,
  } as any)
const platformOwnerDashboardIndexRoute =
  platformOwnerDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => platformOwnerDashboardRouteRoute,
  } as any)
const platformAdminElectionsIndexRoute =
  platformAdminElectionsIndexRouteImport.update({
    id: '/elections/',
    path: '/elections/',
    getParentRoute: () => platformAdminRouteRoute,
  } as any)
const platformAdminApprovalIndexRoute =
  platformAdminApprovalIndexRouteImport.update({
    id: '/approval/',
    path: '/approval/',
    getParentRoute: () => platformAdminRouteRoute,
  } as any)
const platformAdminElectionsNewRoute =
  platformAdminElectionsNewRouteImport.update({
    id: '/elections/new',
    path: '/elections/new',
    getParentRoute: () => platformAdminRouteRoute,
  } as any)
const platformAdminElectionsElectionIdIndexRoute =
  platformAdminElectionsElectionIdIndexRouteImport.update({
    id: '/elections/$electionId/',
    path: '/elections/$electionId/',
    getParentRoute: () => platformAdminRouteRoute,
  } as any)
const platformAdminElectionsElectionIdEditIndexRoute =
  platformAdminElectionsElectionIdEditIndexRouteImport.update({
    id: '/elections/$electionId/edit/',
    path: '/elections/$electionId/edit/',
    getParentRoute: () => platformAdminRouteRoute,
  } as any)
const ApiRpcSplatServerRoute = ApiRpcSplatServerRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof platformRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/admin': typeof platformAdminRouteRouteWithChildren
  '/dashboard': typeof platformDashboardRouteRouteWithChildren
  '/auth/$pathname': typeof AuthPathnameRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/owner/dashboard': typeof platformOwnerDashboardRouteRouteWithChildren
  '/admin/': typeof platformAdminIndexRoute
  '/dashboard/': typeof platformDashboardIndexRoute
  '/admin/elections/new': typeof platformAdminElectionsNewRoute
  '/admin/approval': typeof platformAdminApprovalIndexRoute
  '/admin/elections': typeof platformAdminElectionsIndexRoute
  '/owner/dashboard/': typeof platformOwnerDashboardIndexRoute
  '/admin/elections/$electionId': typeof platformAdminElectionsElectionIdIndexRoute
  '/admin/elections/$electionId/edit': typeof platformAdminElectionsElectionIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof platformRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/$pathname': typeof AuthPathnameRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/admin': typeof platformAdminIndexRoute
  '/dashboard': typeof platformDashboardIndexRoute
  '/admin/elections/new': typeof platformAdminElectionsNewRoute
  '/admin/approval': typeof platformAdminApprovalIndexRoute
  '/admin/elections': typeof platformAdminElectionsIndexRoute
  '/owner/dashboard': typeof platformOwnerDashboardIndexRoute
  '/admin/elections/$electionId': typeof platformAdminElectionsElectionIdIndexRoute
  '/admin/elections/$electionId/edit': typeof platformAdminElectionsElectionIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(platform)': typeof platformRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/(platform)/admin': typeof platformAdminRouteRouteWithChildren
  '/(platform)/dashboard': typeof platformDashboardRouteRouteWithChildren
  '/auth/$pathname': typeof AuthPathnameRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/(platform)/owner/dashboard': typeof platformOwnerDashboardRouteRouteWithChildren
  '/(platform)/admin/': typeof platformAdminIndexRoute
  '/(platform)/dashboard/': typeof platformDashboardIndexRoute
  '/(platform)/admin/elections/new': typeof platformAdminElectionsNewRoute
  '/(platform)/admin/approval/': typeof platformAdminApprovalIndexRoute
  '/(platform)/admin/elections/': typeof platformAdminElectionsIndexRoute
  '/(platform)/owner/dashboard/': typeof platformOwnerDashboardIndexRoute
  '/(platform)/admin/elections/$electionId/': typeof platformAdminElectionsElectionIdIndexRoute
  '/(platform)/admin/elections/$electionId/edit/': typeof platformAdminElectionsElectionIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/dashboard'
    | '/auth/$pathname'
    | '/onboarding/'
    | '/owner/dashboard'
    | '/admin/'
    | '/dashboard/'
    | '/admin/elections/new'
    | '/admin/approval'
    | '/admin/elections'
    | '/owner/dashboard/'
    | '/admin/elections/$electionId'
    | '/admin/elections/$electionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/$pathname'
    | '/onboarding'
    | '/admin'
    | '/dashboard'
    | '/admin/elections/new'
    | '/admin/approval'
    | '/admin/elections'
    | '/owner/dashboard'
    | '/admin/elections/$electionId'
    | '/admin/elections/$electionId/edit'
  id:
    | '__root__'
    | '/(platform)'
    | '/auth'
    | '/onboarding'
    | '/(platform)/admin'
    | '/(platform)/dashboard'
    | '/auth/$pathname'
    | '/onboarding/'
    | '/(platform)/owner/dashboard'
    | '/(platform)/admin/'
    | '/(platform)/dashboard/'
    | '/(platform)/admin/elections/new'
    | '/(platform)/admin/approval/'
    | '/(platform)/admin/elections/'
    | '/(platform)/owner/dashboard/'
    | '/(platform)/admin/elections/$electionId/'
    | '/(platform)/admin/elections/$electionId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  platformRouteRoute: typeof platformRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$' | '/api/rpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$' | '/api/rpc/$'
  id: '__root__' | '/api/auth/$' | '/api/rpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiRpcSplatServerRoute: typeof ApiRpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(platform)': {
      id: '/(platform)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof platformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(platform)/dashboard': {
      id: '/(platform)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof platformDashboardRouteRouteImport
      parentRoute: typeof platformRouteRoute
    }
    '/(platform)/admin': {
      id: '/(platform)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof platformAdminRouteRouteImport
      parentRoute: typeof platformRouteRoute
    }
    '/(platform)/dashboard/': {
      id: '/(platform)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof platformDashboardIndexRouteImport
      parentRoute: typeof platformDashboardRouteRoute
    }
    '/(platform)/admin/': {
      id: '/(platform)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof platformAdminIndexRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/owner/dashboard': {
      id: '/(platform)/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof platformOwnerDashboardRouteRouteImport
      parentRoute: typeof platformRouteRoute
    }
    '/(platform)/owner/dashboard/': {
      id: '/(platform)/owner/dashboard/'
      path: '/'
      fullPath: '/owner/dashboard/'
      preLoaderRoute: typeof platformOwnerDashboardIndexRouteImport
      parentRoute: typeof platformOwnerDashboardRouteRoute
    }
    '/(platform)/admin/elections/': {
      id: '/(platform)/admin/elections/'
      path: '/elections'
      fullPath: '/admin/elections'
      preLoaderRoute: typeof platformAdminElectionsIndexRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/approval/': {
      id: '/(platform)/admin/approval/'
      path: '/approval'
      fullPath: '/admin/approval'
      preLoaderRoute: typeof platformAdminApprovalIndexRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/elections/new': {
      id: '/(platform)/admin/elections/new'
      path: '/elections/new'
      fullPath: '/admin/elections/new'
      preLoaderRoute: typeof platformAdminElectionsNewRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/elections/$electionId/': {
      id: '/(platform)/admin/elections/$electionId/'
      path: '/elections/$electionId'
      fullPath: '/admin/elections/$electionId'
      preLoaderRoute: typeof platformAdminElectionsElectionIdIndexRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/elections/$electionId/edit/': {
      id: '/(platform)/admin/elections/$electionId/edit/'
      path: '/elections/$electionId/edit'
      fullPath: '/admin/elections/$electionId/edit'
      preLoaderRoute: typeof platformAdminElectionsElectionIdEditIndexRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface platformAdminRouteRouteChildren {
  platformAdminIndexRoute: typeof platformAdminIndexRoute
  platformAdminElectionsNewRoute: typeof platformAdminElectionsNewRoute
  platformAdminApprovalIndexRoute: typeof platformAdminApprovalIndexRoute
  platformAdminElectionsIndexRoute: typeof platformAdminElectionsIndexRoute
  platformAdminElectionsElectionIdIndexRoute: typeof platformAdminElectionsElectionIdIndexRoute
  platformAdminElectionsElectionIdEditIndexRoute: typeof platformAdminElectionsElectionIdEditIndexRoute
}

const platformAdminRouteRouteChildren: platformAdminRouteRouteChildren = {
  platformAdminIndexRoute: platformAdminIndexRoute,
  platformAdminElectionsNewRoute: platformAdminElectionsNewRoute,
  platformAdminApprovalIndexRoute: platformAdminApprovalIndexRoute,
  platformAdminElectionsIndexRoute: platformAdminElectionsIndexRoute,
  platformAdminElectionsElectionIdIndexRoute:
    platformAdminElectionsElectionIdIndexRoute,
  platformAdminElectionsElectionIdEditIndexRoute:
    platformAdminElectionsElectionIdEditIndexRoute,
}

const platformAdminRouteRouteWithChildren =
  platformAdminRouteRoute._addFileChildren(platformAdminRouteRouteChildren)

interface platformDashboardRouteRouteChildren {
  platformDashboardIndexRoute: typeof platformDashboardIndexRoute
}

const platformDashboardRouteRouteChildren: platformDashboardRouteRouteChildren =
  {
    platformDashboardIndexRoute: platformDashboardIndexRoute,
  }

const platformDashboardRouteRouteWithChildren =
  platformDashboardRouteRoute._addFileChildren(
    platformDashboardRouteRouteChildren,
  )

interface platformOwnerDashboardRouteRouteChildren {
  platformOwnerDashboardIndexRoute: typeof platformOwnerDashboardIndexRoute
}

const platformOwnerDashboardRouteRouteChildren: platformOwnerDashboardRouteRouteChildren =
  {
    platformOwnerDashboardIndexRoute: platformOwnerDashboardIndexRoute,
  }

const platformOwnerDashboardRouteRouteWithChildren =
  platformOwnerDashboardRouteRoute._addFileChildren(
    platformOwnerDashboardRouteRouteChildren,
  )

interface platformRouteRouteChildren {
  platformAdminRouteRoute: typeof platformAdminRouteRouteWithChildren
  platformDashboardRouteRoute: typeof platformDashboardRouteRouteWithChildren
  platformOwnerDashboardRouteRoute: typeof platformOwnerDashboardRouteRouteWithChildren
}

const platformRouteRouteChildren: platformRouteRouteChildren = {
  platformAdminRouteRoute: platformAdminRouteRouteWithChildren,
  platformDashboardRouteRoute: platformDashboardRouteRouteWithChildren,
  platformOwnerDashboardRouteRoute:
    platformOwnerDashboardRouteRouteWithChildren,
}

const platformRouteRouteWithChildren = platformRouteRoute._addFileChildren(
  platformRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthPathnameRoute: typeof AuthPathnameRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthPathnameRoute: AuthPathnameRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  platformRouteRoute: platformRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiRpcSplatServerRoute: ApiRpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
